#!/bin/bash
#
# Script for running the BLOG inference engine.  Typical usage:
#
# blog [options] <blog-files>
# 
# By default it will use LWSampler (parental likelihood-weighting algorithm).
# To use MHSampler (parental Metropolis-Hasting algorithm), 
#   blog -s blog.sampler.MHSampler [options] <blog-files>
#
# Optional flags:
# -r, --[no]randomize           Use clock time as random seed
# -e <s>, --engine <s>          Use inference engine class <s>
# -n <n>, --num_samples <n>     Run inference engine for <n> samples
# -q <n>, --query_report_interval <n>Report Query values after <n> samples
# -i <n>, --interval <n>        Write results after every <n> samples
# -b <n>, --burn_in <n>         Treat first <n> samples as burn-in
# -s <s>, --sampler <s>         Use sampler class <s>
# -p <s>, --proposer <s>        Use Metropolis-Hastings proposer class <s>
# -t <n>, --num_trials <n>      Do <n> independent runs of inference
# --[no]generate                Sample worlds from prior and print them
# --max_timestep <n>            If model is dynamic, generate up to <n> timesteps
# -k <s>, --package <s>         Parser looks for classes in package <s>
# -v, --[no]verbose             Print info about every world sampled
# -d, --[no]displaycbn          Print the CBN of the sampled world
# -g, --[no]debug               Print model, evidence, and queries
# -w <s>, --write <s>           Write sampling results to file <s>
# -h <s>, --histogram_output <s>Write histogram output to file <s>
# -P<key>=<value>               Set inference configuration properties
# -x <s>, --extend <s>          Extend setup with object of class <s>
# -m <n>, --num_moves <n>       Use <m> moves per rejuvenation step (PF only)
#

BLOG_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export BLOG_HOME

J_PATH_SEP=`${BLOG_HOME}/path_sep.sh`

if [ -d "${BLOG_HOME}/bin" ]; then
  CPATH="${BLOG_HOME}/bin${J_PATH_SEP}${BLOG_HOME}/*"
else 
  CPATH="${BLOG_HOME}/*"
fi

CPATH="${CPATH}${J_PATH_SEP}${BLOG_HOME}/lib/*"

java -cp ${CPATH} -Xmx4096M blog.Main $@
