#!/usr/bin/env bash
#
# Script for running the BLOG inference engine.  Typical usage:
#
# blog [options] <blog-files>
# 
# Please refer to BLOG user manual for the full list of options
#

realpath () {
(
  TARGET_FILE="$1"
  CHECK_CYGWIN="$2"

  cd $(dirname "$TARGET_FILE")
  TARGET_FILE=$(basename "$TARGET_FILE")

  COUNT=0
  while [ -L "$TARGET_FILE" -a $COUNT -lt 100 ]
  do
      TARGET_FILE=$(readlink "$TARGET_FILE")
      cd $(dirname "$TARGET_FILE")
      TARGET_FILE=$(basename "$TARGET_FILE")
      COUNT=$(($COUNT + 1))
  done

  if [ "$TARGET_FILE" == "." -o "$TARGET_FILE" == ".." ]; then
    cd "$TARGET_FILE"
    TARGET_FILEPATH=
  else
    TARGET_FILEPATH=/$TARGET_FILE
  fi

  # make sure we grab the actual windows path, instead of cygwin's path.
  if [[ "x$CHECK_CYGWIN" == "x" ]]; then
    echo "$(pwd -P)/$TARGET_FILE"
  else
    echo $(cygwinpath "$(pwd -P)/$TARGET_FILE")
  fi
)
}

CUR_SCRIPT="$(realpath "$0")"

BLOG_HOME="$(dirname "$CUR_SCRIPT")"

BLOG_SCRIPT="${BLOG_HOME}/target/universal/stage/bin/blog"

if [ ! -e "${BLOG_SCRIPT}" ]; then
  sbt/sbt stage
fi

"${BLOG_SCRIPT}" $@
