#!/bin/bash
#
# Script for running the BLOG inference engine.  Typical usage:
#
# blog [options] <blog-files>
# 
# Please refer to BLOG user manual for the full list of options
#

BLOG_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export BLOG_HOME

J_PATH_SEP=`${BLOG_HOME}/path_sep.sh`

if [ -d "${BLOG_HOME}/bin" ]; then
  CPATH="${BLOG_HOME}/bin${J_PATH_SEP}${BLOG_HOME}/*"
else 
  CPATH="${BLOG_HOME}/*"
fi

CPATH="${CPATH}${J_PATH_SEP}${BLOG_HOME}/lib/*${J_PATH_SEP}${CLASSPATH}"

java -cp ${CPATH} -Xmx4096M blog.Main $@
