#!/bin/bash

BLOG_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export BLOG_HOME

J_PATH_SEP=`${BLOG_HOME}/path_sep.sh`

if [ -d "${BLOG_HOME}/bin" ]; then
  CPATH="${BLOG_HOME}/bin${J_PATH_SEP}${BLOG_HOME}/*"
else
  CPATH="${BLOG_HOME}/*"
fi

CPATH="${CPATH}${J_PATH_SEP}${BLOG_HOME}/lib/*${J_PATH_SEP}${CLASSPATH}${J_PATH_SEP}."
echo $CPATH

JAVA_OPTS="-Xmx4096M" scala -cp ${CPATH} -i iblog.scala $@
