#!/bin/bash

BLOG_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -d "${BLOG_HOME}/src/" ]; then
  BLOG_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../ && pwd )"	
fi

export BLOG_HOME

echo "Starting Interative Shell for BLOG"
if [ -e "${BLOG_HOME}/bin/iblog.scala" ]; then
  CPATH="${BLOG_HOME}/lib/java-cup-11b.jar:${BLOG_HOME}/lib/*:${CLASSPATH}"
  JAVA_OPTS="-Xmx4096M" scala -cp ${CPATH} -i "${BLOG_HOME}/bin/iblog.scala" $@  
else
	CPATH="${BLOG_HOME}/target/universal/stage/lib/java-cup-11b.jar:${BLOG_HOME}/target/universal/stage/lib/*:${CLASSPATH}"
  JAVA_OPTS="-Xmx4096M" scala -cp ${CPATH} -i "${BLOG_HOME}/src/main/scala/iblog.scala" $@  
fi
