#!/bin/bash
#
# Run BLOG using scala. This just sets the right classpath automatically.

BLOG_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export BLOG_HOME

J_PATH_SEP=`${BLOG_HOME}/path_sep.sh`

if [ -d "${BLOG_HOME}/bin" ]; then
  CPATH="${BLOG_HOME}/bin${J_PATH_SEP}${BLOG_HOME}/*"
else
  CPATH="${BLOG_HOME}/*"
fi

CPATH="${CPATH}${J_PATH_SEP}${BLOG_HOME}/lib/*${J_PATH_SEP}${CLASSPATH}"
echo "CPATH: ${CPATH}"

JAVA_OPTS="-Xmx4096M" scala -cp ${CPATH} blog.Main $@
