
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 01 06:26:02 PDT 2013
//----------------------------------------------------

package blog.engine.onlinePF.parser;

/** CUP generated class containing symbol constants. */
public class PolicyTokenConstants {
  /* terminals */
  public static final int GEQ = 15;
  public static final int LT = 12;
  public static final int ELSE = 3;
  public static final int RBRACE = 22;
  public static final int RPAREN = 20;
  public static final int SEMI = 18;
  public static final int BOOLEAN_LITERAL = 10;
  public static final int IF = 4;
  public static final int LBRACE = 21;
  public static final int LPAREN = 19;
  public static final int GT = 13;
  public static final int STRING_LITERAL = 11;
  public static final int INT_LITERAL = 8;
  public static final int EOF = 0;
  public static final int ELSEIF = 5;
  public static final int error = 1;
  public static final int ASSIGN = 7;
  public static final int LEQ = 14;
  public static final int EQEQ = 16;
  public static final int FOR = 6;
  public static final int NULL = 2;
  public static final int NEQ = 17;
  public static final int DOUBLE_LITERAL = 9;
}

