
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 25 02:06:46 PDT 2013
//----------------------------------------------------

package blog.engine.onlinePF.parser;

/** CUP generated class containing symbol constants. */
public class PolicyTokenConstants {
  /* terminals */
  public static final int GEQ = 13;
  public static final int LT = 10;
  public static final int ELSE = 3;
  public static final int RBRACE = 20;
  public static final int RPAREN = 18;
  public static final int SEMI = 16;
  public static final int BOOLEAN_LITERAL = 8;
  public static final int IF = 4;
  public static final int LBRACE = 19;
  public static final int LPAREN = 17;
  public static final int GT = 11;
  public static final int STRING_LITERAL = 9;
  public static final int INT_LITERAL = 6;
  public static final int EOF = 0;
  public static final int ELSEIF = 5;
  public static final int error = 1;
  public static final int LEQ = 12;
  public static final int EQEQ = 14;
  public static final int NULL = 2;
  public static final int NEQ = 15;
  public static final int DOUBLE_LITERAL = 7;
}

