/* The following code was generated by JFlex 1.4.3 on 3/25/13 2:06 AM */


package blog.engine.onlinePF.parser;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 3/25/13 2:06 AM from the specification file
 * <tt>PolicyLexer.flex</tt>
 */
public class PolicyLexer implements ScannerWithLocInfo, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int CHAR_LIT = 4;
  public static final int YYINITIAL = 0;
  public static final int STR_LIT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\46\1\0\1\6\1\5\22\0\1\6\1\36\1\14"+
    "\4\0\1\15\1\37\1\40\1\13\1\2\1\0\1\2\1\3\1\12"+
    "\4\10\4\7\2\1\1\0\1\43\1\33\1\35\1\34\2\0\4\11"+
    "\1\4\1\21\2\0\1\20\2\0\1\16\6\0\1\17\7\0\1\0"+
    "\1\44\4\0\1\27\1\45\2\11\1\25\1\26\2\0\1\20\2\0"+
    "\1\30\1\0\1\32\3\0\1\23\1\31\1\22\1\24\5\0\1\42"+
    "\1\0\1\41\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\3\1\1\3\1\1\1\4\1\5"+
    "\4\1\1\6\1\7\2\1\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\15\1\20\3\0\1\21"+
    "\1\0\1\22\3\0\1\23\1\24\1\25\1\26\1\27"+
    "\2\30\1\31\1\32\1\33\1\34\1\27\1\35\1\36"+
    "\1\37\1\40\1\20\2\0\1\21\4\0\1\30\1\0"+
    "\1\41\1\42\1\0\1\43\2\0\1\44\1\0\1\45"+
    "\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[75];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\116\0\165\0\234\0\303\0\352"+
    "\0\116\0\u0111\0\116\0\116\0\u0138\0\u015f\0\u0186\0\u01ad"+
    "\0\u01d4\0\u01fb\0\u0222\0\u0249\0\116\0\116\0\116\0\116"+
    "\0\116\0\116\0\116\0\116\0\u0270\0\u0297\0\u02be\0\303"+
    "\0\u02e5\0\u030c\0\u0333\0\116\0\u035a\0\u0381\0\u03a8\0\116"+
    "\0\116\0\116\0\116\0\116\0\u03cf\0\u03f6\0\116\0\116"+
    "\0\116\0\116\0\u041d\0\116\0\116\0\116\0\116\0\u0444"+
    "\0\u0444\0\u046b\0\116\0\u0492\0\u04b9\0\u04e0\0\u0507\0\116"+
    "\0\u052e\0\u0555\0\116\0\u057c\0\116\0\u05a3\0\u05ca\0\116"+
    "\0\u05f1\0\116\0\116";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[75];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\2\11\2\5\1\4"+
    "\1\12\1\4\1\13\1\14\2\4\1\15\1\4\1\16"+
    "\2\4\1\10\1\17\3\4\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\2\4\1\11"+
    "\5\32\1\33\6\32\1\34\27\32\1\35\1\32\1\33"+
    "\50\0\1\5\1\0\1\36\1\37\2\0\2\5\14\0"+
    "\1\37\22\0\1\5\1\0\1\40\3\0\2\5\37\0"+
    "\1\36\5\0\2\36\54\0\1\41\11\0\1\41\30\0"+
    "\1\42\1\43\54\0\1\44\4\0\1\44\43\0\1\45"+
    "\52\0\1\46\43\0\1\47\57\0\1\50\46\0\1\51"+
    "\46\0\1\52\46\0\1\53\11\0\7\54\1\55\1\56"+
    "\3\54\1\57\1\60\4\54\1\61\1\62\1\63\1\54"+
    "\1\64\3\54\1\65\11\54\1\66\1\67\2\0\1\36"+
    "\2\0\1\37\2\0\2\36\14\0\1\37\22\0\1\70"+
    "\1\71\4\0\2\70\55\0\1\72\11\0\1\72\15\0"+
    "\5\42\1\73\40\42\1\73\13\43\1\74\33\43\24\0"+
    "\1\75\52\0\1\76\46\0\1\77\25\0\2\100\45\0"+
    "\2\55\37\0\1\101\2\0\1\101\2\0\3\101\7\0"+
    "\1\101\3\0\3\101\15\0\1\101\2\0\1\70\5\0"+
    "\2\70\42\0\1\102\20\0\1\102\21\0\12\43\1\73"+
    "\1\74\33\43\25\0\1\103\52\0\1\104\45\0\1\105"+
    "\17\0\1\106\2\0\1\106\2\0\3\106\7\0\1\106"+
    "\3\0\3\106\15\0\1\106\21\0\1\107\53\0\1\110"+
    "\22\0\1\111\2\0\1\111\2\0\3\111\7\0\1\111"+
    "\3\0\3\111\15\0\1\111\22\0\1\112\4\0\1\112"+
    "\21\0\1\113\2\0\1\113\2\0\3\113\7\0\1\113"+
    "\3\0\3\113\15\0\1\113\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1560];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\10\1\11\4\1\1\11\1\1\2\11\10\1"+
    "\10\11\2\1\3\0\1\1\1\0\1\11\3\0\5\11"+
    "\2\1\4\11\1\1\4\11\1\1\2\0\1\11\4\0"+
    "\1\11\1\0\1\1\1\11\1\0\1\11\2\0\1\11"+
    "\1\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[75];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  // For assembling string and character constants
  StringBuffer string_buf = new StringBuffer();

  // For line numbers
  public int getCurLineNum() {
    return yyline;
  }
  
  public int getCurColNum() {
    return yycolumn;
  }

  private String filename;

  public void setFilename(String fname) {
    filename = fname;
  }

  public String getCurFilename() {
    return filename;
  }
  
  
  private Symbol symbol(int type) {
    return symbol(type, null);
  }

  private Symbol symbol(int type, Object value) {
    return new PolicySymbol(type, getCurLineNum(), getCurColNum(), yychar, yychar+yylength(), value);

  }
  



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PolicyLexer(java.io.Reader in) {
      // empty for now
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public PolicyLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 126) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { /* ignore */
          }
        case 39: break;
        case 24: 
          { int code = Integer.parseInt(yytext().substring(1), 8);
         string_buf.append((char) code);
          }
        case 40: break;
        case 36: 
          { return symbol(PolicyTokenConstants.BOOLEAN_LITERAL, new Boolean(false));
          }
        case 41: break;
        case 22: 
          { return symbol(PolicyTokenConstants.NEQ);
          }
        case 42: break;
        case 2: 
          { return symbol(PolicyTokenConstants.INT_LITERAL, new Integer(yytext()));
          }
        case 43: break;
        case 4: 
          { yybegin (STR_LIT);
          }
        case 44: break;
        case 18: 
          { return symbol(PolicyTokenConstants.IF);
          }
        case 45: break;
        case 1: 
          { return symbol(PolicyTokenConstants.error, 
                                          yytext());
          }
        case 46: break;
        case 9: 
          { return symbol(PolicyTokenConstants.RPAREN);
          }
        case 47: break;
        case 27: 
          { string_buf.append('\t');
          }
        case 48: break;
        case 11: 
          { return symbol(PolicyTokenConstants.LBRACE);
          }
        case 49: break;
        case 31: 
          { string_buf.append('\\');
          }
        case 50: break;
        case 34: 
          { return symbol(PolicyTokenConstants.BOOLEAN_LITERAL, new Boolean(true));
          }
        case 51: break;
        case 33: 
          { return symbol(PolicyTokenConstants.ELSE);
          }
        case 52: break;
        case 28: 
          { string_buf.append('\r');
          }
        case 53: break;
        case 29: 
          { string_buf.append('\f');
          }
        case 54: break;
        case 3: 
          { /* Do nothing */
          }
        case 55: break;
        case 16: 
          { return 
		 symbol(PolicyTokenConstants.DOUBLE_LITERAL, new Double(yytext()));
          }
        case 56: break;
        case 19: 
          { return symbol(PolicyTokenConstants.LEQ);
          }
        case 57: break;
        case 25: 
          { string_buf.append('\"');
          }
        case 58: break;
        case 37: 
          { return symbol(PolicyTokenConstants.ELSEIF);
          }
        case 59: break;
        case 14: 
          { return symbol(PolicyTokenConstants.error, 
                         "Line terminator in string or character literal.");
          }
        case 60: break;
        case 15: 
          { /* closing double-quote not matched by \" rule below */
       Symbol s =   symbol(PolicyTokenConstants.STRING_LITERAL, 
			       string_buf.toString());
       string_buf = new StringBuffer(); /* reinitialize the buffer */
       yybegin(YYINITIAL);
       return s;
          }
        case 61: break;
        case 12: 
          { return symbol(PolicyTokenConstants.SEMI);
          }
        case 62: break;
        case 26: 
          { string_buf.append('\'');
          }
        case 63: break;
        case 8: 
          { return symbol(PolicyTokenConstants.LPAREN);
          }
        case 64: break;
        case 7: 
          { return symbol(PolicyTokenConstants.GT);
          }
        case 65: break;
        case 30: 
          { string_buf.append('\n');
          }
        case 66: break;
        case 6: 
          { return symbol(PolicyTokenConstants.LT);
          }
        case 67: break;
        case 5: 
          { yybegin (CHAR_LIT);
          }
        case 68: break;
        case 10: 
          { return symbol(PolicyTokenConstants.RBRACE);
          }
        case 69: break;
        case 32: 
          { string_buf.append('\b');
          }
        case 70: break;
        case 13: 
          { /* Char in quotes, not matched by any rule above */
       string_buf.append(yytext());
          }
        case 71: break;
        case 21: 
          { return symbol(PolicyTokenConstants.EQEQ);
          }
        case 72: break;
        case 35: 
          { return symbol(PolicyTokenConstants.NULL);
          }
        case 73: break;
        case 20: 
          { return symbol(PolicyTokenConstants.GEQ);
          }
        case 74: break;
        case 38: 
          { int code = Integer.parseInt(yytext().substring(2), 16);
       string_buf.append((char) code);
          }
        case 75: break;
        case 23: 
          { return symbol(PolicyTokenConstants.error, 
                         "Unrecognized escape character: \'" 
                         + yytext() + "\'");
          }
        case 76: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {   switch(yystate()) {
    case YYINITIAL:
    /* nothing special to do in the initial state */
      break;
    case STR_LIT:
    case CHAR_LIT:
      return symbol(PolicyTokenConstants.error, 
                        "File ended before string or character literal "
                        + "was terminated.");

  }
  /* Reinitialize everything before signaling EOF */
  string_buf = new StringBuffer();
  yybegin(YYINITIAL);
  return symbol(PolicyTokenConstants.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
