
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Sep 18 21:56:33 PDT 2013
//----------------------------------------------------

package blog.engine.onlinePF.parser;

/** CUP generated class containing symbol constants. */
public class PolicyTokenConstants {
  /* terminals */
  public static final int GEQ = 14;
  public static final int LT = 11;
  public static final int ELSE = 3;
  public static final int RBRACE = 21;
  public static final int RPAREN = 19;
  public static final int SEMI = 17;
  public static final int BOOLEAN_LITERAL = 9;
  public static final int IF = 4;
  public static final int LBRACE = 20;
  public static final int LPAREN = 18;
  public static final int GT = 12;
  public static final int STRING_LITERAL = 10;
  public static final int INT_LITERAL = 7;
  public static final int EOF = 0;
  public static final int ELSEIF = 5;
  public static final int error = 1;
  public static final int LEQ = 13;
  public static final int EQEQ = 15;
  public static final int FOR = 6;
  public static final int NULL = 2;
  public static final int NEQ = 16;
  public static final int DOUBLE_LITERAL = 8;
}

