
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Sun Jun 22 02:52:20 PDT 2014
//----------------------------------------------------

package blog.parse;

/** CUP generated class containing symbol constants. */
public class BLOGTokenConstants {
  /* terminals */
  public static final int FORALL = 17;
  public static final int MAP = 14;
  public static final int QUERY = 10;
  public static final int STRING_LITERAL = 24;
  public static final int LBRACKET = 55;
  public static final int POWER = 32;
  public static final int MULT = 29;
  public static final int RANDOM = 6;
  public static final int CHAR_LITERAL = 23;
  public static final int LPAREN = 51;
  public static final int SEMI = 46;
  public static final int FOR = 18;
  public static final int MINUS = 28;
  public static final int PARAM = 12;
  public static final int RPAREN = 52;
  public static final int BOOLEAN_LITERAL = 22;
  public static final int AND = 42;
  public static final int NOT = 41;
  public static final int LT = 33;
  public static final int TYPE = 5;
  public static final int OR = 43;
  public static final int COMMA = 45;
  public static final int DISTRIBUTION = 15;
  public static final int FIXED = 7;
  public static final int DIV = 30;
  public static final int GEQ = 36;
  public static final int PLUS = 27;
  public static final int ORIGIN = 8;
  public static final int OBS = 11;
  public static final int IF = 3;
  public static final int DOT = 48;
  public static final int ID = 25;
  public static final int EOF = 0;
  public static final int RBRACKET = 56;
  public static final int error = 1;
  public static final int DISTINCT = 9;
  public static final int EQEQ = 37;
  public static final int NULL = 19;
  public static final int EXISTS = 16;
  public static final int MOD = 31;
  public static final int NEQ = 38;
  public static final int DISTRIB = 40;
  public static final int NUMSIGN = 49;
  public static final int EQ = 39;
  public static final int COLON = 47;
  public static final int LBRACE = 53;
  public static final int ELSE = 2;
  public static final int LIST = 13;
  public static final int RBRACE = 54;
  public static final int THEN = 4;
  public static final int LEQ = 35;
  public static final int RIGHTARROW = 50;
  public static final int DOUBLERIGHTARROW = 44;
  public static final int DOUBLE_LITERAL = 21;
  public static final int AT = 26;
  public static final int GT = 34;
  public static final int INT_LITERAL = 20;
}

