
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Sun Jun 22 22:24:04 PDT 2014
//----------------------------------------------------

package blog.parse;

/** CUP generated class containing symbol constants. */
public class BLOGTokenConstants {
  /* terminals */
  public static final int FORALL = 18;
  public static final int MAP = 15;
  public static final int QUERY = 11;
  public static final int STRING_LITERAL = 25;
  public static final int LBRACKET = 57;
  public static final int POWER = 33;
  public static final int MULT = 30;
  public static final int RANDOM = 7;
  public static final int CHAR_LITERAL = 24;
  public static final int UMINUS = 34;
  public static final int CASE = 5;
  public static final int LPAREN = 53;
  public static final int SEMI = 48;
  public static final int FOR = 19;
  public static final int MINUS = 29;
  public static final int PARAM = 13;
  public static final int RPAREN = 54;
  public static final int BOOLEAN_LITERAL = 23;
  public static final int AND = 44;
  public static final int NOT = 43;
  public static final int LT = 35;
  public static final int TYPE = 6;
  public static final int OR = 45;
  public static final int COMMA = 47;
  public static final int DISTRIBUTION = 16;
  public static final int FIXED = 8;
  public static final int DIV = 31;
  public static final int GEQ = 38;
  public static final int PLUS = 28;
  public static final int ORIGIN = 9;
  public static final int OBS = 12;
  public static final int IF = 3;
  public static final int DOT = 50;
  public static final int ID = 26;
  public static final int EOF = 0;
  public static final int RBRACKET = 58;
  public static final int error = 1;
  public static final int DISTINCT = 10;
  public static final int EQEQ = 39;
  public static final int NULL = 20;
  public static final int EXISTS = 17;
  public static final int MOD = 32;
  public static final int NEQ = 40;
  public static final int DISTRIB = 42;
  public static final int NUMSIGN = 51;
  public static final int EQ = 41;
  public static final int COLON = 49;
  public static final int LBRACE = 55;
  public static final int ELSE = 2;
  public static final int LIST = 14;
  public static final int RBRACE = 56;
  public static final int THEN = 4;
  public static final int LEQ = 37;
  public static final int RIGHTARROW = 52;
  public static final int DOUBLERIGHTARROW = 46;
  public static final int DOUBLE_LITERAL = 22;
  public static final int AT = 27;
  public static final int GT = 36;
  public static final int INT_LITERAL = 21;
}

