<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>blog</string>
		<string>dblog</string>
		<string>mblog</string>
		<string>eblog</string>
		<string>qblog</string>
	</array>
	<key>name</key>
	<string>BLOG</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\s*((//).*$\n?)</string>
			<key>name</key>
			<string>comment.line.double-slash.blog</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(/\*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.blog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.blog</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.blog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.blog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.blog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\#)(\w+)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-\&gt;|\&lt;|\&gt;|\=|\=\=|\&gt;\=|\&lt;\=|\!|~|:|\+|\-|\*|\/|\%|\=\&gt;|\&amp;|\||\[|\])</string>
			<key>name</key>
			<string>keyword.operator.blog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(obs|query)\b</string>
			<key>name</key>
			<string>storage.modifer.blog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.blog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.primitive.blog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(fixed|random|origin)\b\s+\b(Integer|Real|Boolean|NaturalNum|Timestep|RealMatrix|IntegerMatrix|\w+)((\[\])*)\s+</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.blog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.blog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(distinct)\s+(\w+)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.blog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.blog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(type)\s+(\w+)(\s*\,\s*(\w+))*\s*</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Integer|Real|Boolean|NaturalNum|Timestep|RealMatrix|IntegerMatrix)((\[\])*)\b</string>
			<key>name</key>
			<string>storage.type.primitive.blog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|then|else|case|in|forall|exists|for)\b</string>
			<key>name</key>
			<string>keyword.control.blog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abs|round|inv|transpose|det|repmat|diag|vstack|hstack|eye|zeros|ones|exp|toReal|toInt|isEmptyString|prev|min|max|sum)\b</string>
			<key>name</key>
			<string>support.function.blog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(TabularCPD|Distribution|Gaussian|UniformChoice|MultivarGaussian|Poisson|Bernoulli|BooleanDistrib|Binomial|Beta|BoundedGenometric|Categorical|Dirichlet|EqualsCPD|Gamma|Geometric|Iota|LinearGaussian|MixtureDistrib|NegativeBinamial|RoundedLogNormal|TabularInterp|UniformVector|UnivarGaussian|Exponential|UniformInt|UniformReal|Multinomial|Laplace)\b</string>
			<key>name</key>
			<string>support.class.blog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFfUuDd]|UL|ul)?\b</string>
			<key>name</key>
			<string>constant.numeric.blog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\@[0-9]+</string>
			<key>name</key>
			<string>constant.other.blog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.blog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>punctuation.terminator.blog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.blog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(\w+)\(</string>
			<key>name</key>
			<string>function.blog</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.blog</string>
	<key>uuid</key>
	<string>99d32618-4b9c-4a4c-b44b-fb8851e307be</string>
</dict>
</plist>
