
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Thu Sep 25 23:44:12 PDT 2014
//----------------------------------------------------

package blog.parse;

/** CUP generated class containing symbol constants. */
public class BLOGTokenConstants {
  /* terminals */
  public static final int FORALL = 20;
  public static final int MAP = 16;
  public static final int QUERY = 12;
  public static final int STRING_LITERAL = 27;
  public static final int LBRACKET = 59;
  public static final int POWER = 35;
  public static final int MULT = 32;
  public static final int RANDOM = 8;
  public static final int CHAR_LITERAL = 26;
  public static final int UMINUS = 36;
  public static final int CASE = 5;
  public static final int LPAREN = 55;
  public static final int SEMI = 50;
  public static final int FOR = 21;
  public static final int MINUS = 31;
  public static final int PARAM = 14;
  public static final int RPAREN = 56;
  public static final int BOOLEAN_LITERAL = 25;
  public static final int AND = 46;
  public static final int NOT = 45;
  public static final int LT = 37;
  public static final int TYPE = 7;
  public static final int OR = 47;
  public static final int IN = 6;
  public static final int COMMA = 49;
  public static final int DISTRIBUTION = 17;
  public static final int FIXED = 9;
  public static final int DIV = 33;
  public static final int GEQ = 40;
  public static final int EXTERN = 18;
  public static final int PLUS = 30;
  public static final int ORIGIN = 10;
  public static final int OBS = 13;
  public static final int IF = 3;
  public static final int DOT = 52;
  public static final int ID = 28;
  public static final int EOF = 0;
  public static final int RBRACKET = 60;
  public static final int error = 1;
  public static final int DISTINCT = 11;
  public static final int EQEQ = 41;
  public static final int NULL = 22;
  public static final int EXISTS = 19;
  public static final int MOD = 34;
  public static final int NEQ = 42;
  public static final int DISTRIB = 44;
  public static final int NUMSIGN = 53;
  public static final int EQ = 43;
  public static final int COLON = 51;
  public static final int LBRACE = 57;
  public static final int ELSE = 2;
  public static final int LIST = 15;
  public static final int RBRACE = 58;
  public static final int THEN = 4;
  public static final int LEQ = 39;
  public static final int RIGHTARROW = 54;
  public static final int DOUBLERIGHTARROW = 48;
  public static final int DOUBLE_LITERAL = 24;
  public static final int AT = 29;
  public static final int GT = 38;
  public static final int INT_LITERAL = 23;
}

