package blog.sample;

import blog.world.PartialWorld;

/**
 * A sample generated by LWSampler.
 * 
 * @author cberzan
 * @since Jun 19, 2014
 */
public class LWSample {
  public PartialWorld world;
  public double logWeight;
}
