package blog.debug

import blog.model.Model
import blog.world.PartialWorld

/**
 * A sample generated by LWSampler.
 *
 * @author cberzan
 * @since Jun 23, 2014
 */
class LWSample(model: Model, world: PartialWorld, val logWeight: Double)
  extends Sample(model, world) {

  override def toString = s"LWSample(logWeight: ${logWeight}, world: ${world})"
}
