package test.example;

/**
 * Indicates that an entry in a probability table generated by a BLOG query
 * does not match a corresponding entry in a reference table in a test.
 * 
 * @author awong
 * @date July 14, 2012
 */
public class IncorrectProbException extends Exception {

	public IncorrectProbException() {
		super();
	}

	public IncorrectProbException(String message) {
		super(message);
	}

	public IncorrectProbException(Throwable cause) {
		super(cause);
	}

	public IncorrectProbException(String message, Throwable cause) {
		super(message, cause);
	}
}
